In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Tea and coffee from 2015 to 2020

In [3]:
tea_coffee=pd.read_csv('FAOS_Coffee_Tea_2-11-2023.csv')

In [63]:
region=pd.read_csv('RegionCountry.csv')

#### Analyse of tea_coffee

In [4]:
tea_coffee

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,FBS,Food Balances (2010-),4,Afghanistan,5611,Import Quantity,S2630,Coffee and products,2015,2015,1000 tonnes,0,I,Imputed value
1,FBS,Food Balances (2010-),4,Afghanistan,5611,Import Quantity,S2630,Coffee and products,2016,2016,1000 tonnes,0,I,Imputed value
2,FBS,Food Balances (2010-),4,Afghanistan,5611,Import Quantity,S2630,Coffee and products,2017,2017,1000 tonnes,2,I,Imputed value
3,FBS,Food Balances (2010-),4,Afghanistan,5611,Import Quantity,S2630,Coffee and products,2018,2018,1000 tonnes,1,I,Imputed value
4,FBS,Food Balances (2010-),4,Afghanistan,5611,Import Quantity,S2630,Coffee and products,2019,2019,1000 tonnes,1,I,Imputed value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7851,FBS,Food Balances (2010-),716,Zimbabwe,5301,Domestic supply quantity,S2635,Tea (including mate),2016,2016,1000 tonnes,-9,I,Imputed value
7852,FBS,Food Balances (2010-),716,Zimbabwe,5301,Domestic supply quantity,S2635,Tea (including mate),2017,2017,1000 tonnes,-12,I,Imputed value
7853,FBS,Food Balances (2010-),716,Zimbabwe,5301,Domestic supply quantity,S2635,Tea (including mate),2018,2018,1000 tonnes,-13,I,Imputed value
7854,FBS,Food Balances (2010-),716,Zimbabwe,5301,Domestic supply quantity,S2635,Tea (including mate),2019,2019,1000 tonnes,-11,I,Imputed value
7855,FBS,Food Balances (2010-),716,Zimbabwe,5301,Domestic supply quantity,S2635,Tea (including mate),2020,2020,1000 tonnes,-8,I,Imputed value

checking values for each columns

In [5]:
tea_coffee['Domain Code'].unique()

array(['FBS'], dtype=object)

In [6]:
tea_coffee['Domain'].unique()

array(['Food Balances (2010-)'], dtype=object)

In [7]:
tea_coffee['Element'].unique()

array(['Import Quantity', 'Export Quantity', 'Domestic supply quantity',
       'Production', 'Tourist consumption'], dtype=object)

In [8]:
tea_coffee['Item'].unique()

array(['Coffee and products', 'Tea (including mate)'], dtype=object)

In [9]:
tea_coffee['Year'].unique()

array([2015, 2016, 2017, 2018, 2019, 2020], dtype=int64)

In [10]:
tea_coffee['Unit'].unique()

array(['1000 tonnes'], dtype=object)

In [11]:
tea_coffee['Flag'].unique()

array(['I', 'E'], dtype=object)

In [12]:
tea_coffee['Flag Description'].unique()

array(['Imputed value', 'Estimated value'], dtype=object)

#### Delete unusable columns

In [13]:
tea_coffe_20152020=tea_coffee.drop(['Domain Code','Domain','Unit','Flag','Flag Description','Year Code','Item Code (CPC)','Element Code','Area Code (M49)'],axis=1)
tea_coffe_20152020

             Area                   Element                  Item  Year  Value
0     Afghanistan           Import Quantity   Coffee and products  2015      0
1     Afghanistan           Import Quantity   Coffee and products  2016      0
2     Afghanistan           Import Quantity   Coffee and products  2017      2
3     Afghanistan           Import Quantity   Coffee and products  2018      1
4     Afghanistan           Import Quantity   Coffee and products  2019      1
...           ...                       ...                   ...   ...    ...
7851     Zimbabwe  Domestic supply quantity  Tea (including mate)  2016     -9
7852     Zimbabwe  Domestic supply quantity  Tea (including mate)  2017    -12
7853     Zimbabwe  Domestic supply quantity  Tea (including mate)  2018    -13
7854     Zimbabwe  Domestic supply quantity  Tea (including mate)  2019    -11
7855     Zimbabwe  Domestic supply quantity  Tea (including mate)  2020     -8

[7856 rows x 5 columns]

In [61]:
tea_coffe_20152020.head(50)

        Country                   Element                  Item  Year  Value
0   Afghanistan           Import Quantity   Coffee and products  2015      0
1   Afghanistan           Import Quantity   Coffee and products  2016      0
2   Afghanistan           Import Quantity   Coffee and products  2017      2
3   Afghanistan           Import Quantity   Coffee and products  2018      1
4   Afghanistan           Import Quantity   Coffee and products  2019      1
5   Afghanistan           Import Quantity   Coffee and products  2020      2
6   Afghanistan           Export Quantity   Coffee and products  2015      0
7   Afghanistan           Export Quantity   Coffee and products  2016      0
8   Afghanistan           Export Quantity   Coffee and products  2017      0
9   Afghanistan           Export Quantity   Coffee and products  2018      1
10  Afghanistan           Export Quantity   Coffee and products  2019      0
11  Afghanistan           Export Quantity   Coffee and products  2020      4
12  Afghanistan  Domestic supply quantity   Coffee and products  2015      0
13  Afghanistan  Domestic supply quantity   Coffee and products  2016      0
14  Afghanistan  Domestic supply quantity   Coffee and products  2017      0
15  Afghanistan  Domestic supply quantity   Coffee and products  2018      0
16  Afghanistan  Domestic supply quantity   Coffee and products  2019      0
17  Afghanistan  Domestic supply quantity   Coffee and products  2020      0
18  Afghanistan           Import Quantity  Tea (including mate)  2015     72
19  Afghanistan           Import Quantity  Tea (including mate)  2016     52
20  Afghanistan           Import Quantity  Tea (including mate)  2017     80
21  Afghanistan           Import Quantity  Tea (including mate)  2018     81
22  Afghanistan           Import Quantity  Tea (including mate)  2019     76
23  Afghanistan           Import Quantity  Tea (including mate)  2020     15
24  Afghanistan           Export Quantity  Tea (including mate)  2015      0
25  Afghanistan           Export Quantity  Tea (including mate)  2016      0
26  Afghanistan           Export Quantity  Tea (including mate)  2017      1
27  Afghanistan           Export Quantity  Tea (including mate)  2018      0
28  Afghanistan           Export Quantity  Tea (including mate)  2019      0
29  Afghanistan           Export Quantity  Tea (including mate)  2020      0
30  Afghanistan  Domestic supply quantity  Tea (including mate)  2015     90
31  Afghanistan  Domestic supply quantity  Tea (including mate)  2016     51
32  Afghanistan  Domestic supply quantity  Tea (including mate)  2017     79
33  Afghanistan  Domestic supply quantity  Tea (including mate)  2018     81
34  Afghanistan  Domestic supply quantity  Tea (including mate)  2019     76
35  Afghanistan  Domestic supply quantity  Tea (including mate)  2020     15
36      Albania                Production   Coffee and products  2015      0
37      Albania                Production   Coffee and products  2016      0
38      Albania                Production   Coffee and products  2017      0
39      Albania                Production   Coffee and products  2018      0
40      Albania                Production   Coffee and products  2019      0
41      Albania                Production   Coffee and products  2020      0
42      Albania           Import Quantity   Coffee and products  2015      9
43      Albania           Import Quantity   Coffee and products  2016      9
44      Albania           Import Quantity   Coffee and products  2017      6
45      Albania           Import Quantity   Coffee and products  2018      8
46      Albania           Import Quantity   Coffee and products  2019      8
47      Albania           Import Quantity   Coffee and products  2020      8
48      Albania           Export Quantity   Coffee and products  2015      0
49      Albania           Export Quantity   Coffee and products  2016      0

In [14]:
tea_coffe_20152020.shape

(7856, 5)

In [15]:
tea_coffe_20152020.dtypes

Area       object
Element    object
Item       object
Year        int64
Value       int64
dtype: object

In [16]:
tea_coffe_20152020.isnull().sum()

Area       0
Element    0
Item       0
Year       0
Value      0
dtype: int64

In [17]:
tea_coffe_20152020.duplicated().sum()

0

In [18]:
tea_coffe_20152020[tea_coffe_20152020['Element']=="Production"]

          Area     Element                  Item  Year  Value
36     Albania  Production   Coffee and products  2015      0
37     Albania  Production   Coffee and products  2016      0
38     Albania  Production   Coffee and products  2017      0
39     Albania  Production   Coffee and products  2018      0
40     Albania  Production   Coffee and products  2019      0
...        ...         ...                   ...   ...    ...
7833  Zimbabwe  Production  Tea (including mate)  2016      2
7834  Zimbabwe  Production  Tea (including mate)  2017      1
7835  Zimbabwe  Production  Tea (including mate)  2018      1
7836  Zimbabwe  Production  Tea (including mate)  2019      4
7837  Zimbabwe  Production  Tea (including mate)  2020      4

[1073 rows x 5 columns]

In [46]:
pd.set_option('display.max_rows', None)

In [47]:
tea_coffe_20152020[tea_coffe_20152020['Area'].str.contains("China")]

,Area,Element,Item,Year,Value
1331,China,Production,Coffee and products,2015,115
1332,China,Production,Coffee and products,2016,116
1333,China,Production,Coffee and products,2017,116
1334,China,Production,Coffee and products,2018,116
1335,China,Production,Coffee and products,2019,120
1336,China,Production,Coffee and products,2020,114
1337,China,Import Quantity,Coffee and products,2015,184
1338,China,Import Quantity,Coffee and products,2016,286
1339,China,Import Quantity,Coffee and products,2017,269
1340,China,Import Quantity,Coffee and products,2018,224
1341,China,Import Quantity,Coffee and products,2019,225
1342,China,Import Quantity,Coffee and products,2020,235
1343,China,Export Quantity,Coffee and products,2015,162
1344,China,Export Quantity,Coffee and products,2016,246
1345,China,Export Quantity,Coffee and products,2017,182
1346,China,Export Quantity,Coffee and products,2018,173
1347,China,Export Quantity,Coffee and products,2019,132
1348,China,Export Quantity,Coffee and products,2020,79
1349,China,Domestic supply quantity,Coffee and products,2015,90
1350,China,Domestic supply quantity,Coffee and products,2016,93
1351,China,Domestic supply quantity,Coffee and products,2017,103
1352,China,Domestic supply quantity,Coffee and products,2018,133
1353,China,Domestic supply quantity,Coffee and products,2019,146
1354,China,Domestic supply quantity,Coffee and products,2020,211
1355,China,Tourist consumption,Coffee and products,2015,1
1356,China,Tourist consumption,Coffee and products,2016,1
1357,China,Tourist consumption,Coffee and products,2017,2
1358,China,Tourist consumption,Coffee and products,2018,2
1359,China,Tourist consumption,Coffee and products,2019,2
1360,China,Production,Tea (including mate),2015,2291
1361,China,Production,Tea (including mate),2016,2326
1362,China,Production,Tea (including mate),2017,2474
1363,China,Production,Tea (including mate),2018,2625
1364,China,Production,Tea (including mate),2019,2792
1365,China,Production,Tea (including mate),2020,2984
1366,China,Import Quantity,Tea (including mate),2015,72
1367,China,Import Quantity,Tea (including mate),2016,69
1368,China,Import Quantity,Tea (including mate),2017,84
1369,China,Import Quantity,Tea (including mate),2018,95
1370,China,Import Quantity,Tea (including mate),2019,109
1371,China,Import Quantity,Tea (including mate),2020,100
1372,China,Export Quantity,Tea (including mate),2015,346
1373,China,Export Quantity,Tea (including mate),2016,351
1374,China,Export Quantity,Tea (including mate),2017,382
1375,China,Export Quantity,Tea (including mate),2018,397
1376,China,Export Quantity,Tea (including mate),2019,403
1377,China,Export Quantity,Tea (including mate),2020,377
1378,China,Domestic supply quantity,Tea (including mate),2015,1694
1379,China,Domestic supply quantity,Tea (including mate),2016,1727
1380,China,Domestic supply quantity,Tea (including mate),2017,1778
1381,China,Domestic supply quantity,Tea (including mate),2018,1822
1382,China,Domestic supply quantity,Tea (including mate),2019,1975
1383,China,Domestic supply quantity,Tea (including mate),2020,2003
1384,China,Tourist consumption,Tea (including mate),2015,0
1385,China,Tourist consumption,Tea (including mate),2016,0
1386,China,Tourist consumption,Tea (including mate),2017,0
1387,China,Tourist consumption,Tea (including mate),2018,0
1388,China,Tourist consumption,Tea (including mate),2019,0
1389,"China, Hong Kong SAR",Import Quantity,Coffee and products,2015,19
1390,"China, Hong Kong SAR",Import Quantity,Coffee and products,2016,50
1391,"China, Hong Kong SAR",Import Quantity,Coffee and products,2017,74
1392,"China, Hong Kong SAR",Import Quantity,Coffee and products,2018,28
1393,"China, Hong Kong SAR",Import Quantity,Coffee and products,2019,24
1394,"China, Hong Kong SAR",Import Quantity,Coffee and products,2020,21
1395,"China, Hong Kong SAR",Export Quantity,Coffee and products,2015,3
1396,"China, Hong Kong SAR",Export Quantity,Coffee and products,2016,11
1397,"China, Hong Kong SAR",Export Quantity,Coffee and products,2017,21
1398,"China, Hong Kong SAR",Export Quantity,Coffee and products,2018,9
1399,"China, Hong Kong SAR",Export Quantity,Coffee and products,2019,4
1400,"China, Hong Kong SAR",Export Quantity,Coffee and products,2020,3
1401,"China, Hong Kong SAR",Domestic supply quantity,Coffee and products,2015,14
1402,"China, Hong Kong SAR",Domestic supply quantity,Coffee and products,2016,15
1403,"China, Hong Kong SAR",Domestic supply quantity,Coffee and products,2017,15
1404,"China, Hong Kong SAR",Domestic supply quantity,Coffee and products,2018,19
1405,"China, Hong Kong SAR",Domestic supply quantity,Coffee and products,2019,18
1406,"China, Hong Kong SAR",Domestic supply quantity,Coffee and products,2020,16
1407,"China, Hong Kong SAR",Tourist consumption,Coffee and products,2015,1
1408,"China, Hong Kong SAR",Tourist consumption,Coffee and products,2016,1
1409,"China, Hong Kong SAR",Tourist consumption,Coffee and products,2017,2
1410,"China, Hong Kong SAR",Tourist consumption,Coffee and products,2018,2
1411,"China, Hong Kong SAR",Tourist consumption,Coffee and products,2019,2
1412,"China, Hong Kong SAR",Import Quantity,Tea (including mate),2015,15
1413,"China, Hong Kong SAR",Import Quantity,Tea (including mate),2016,16
1414,"China, Hong Kong SAR",Import Quantity,Tea (including mate),2017,19
1415,"China, Hong Kong SAR",Import Quantity,Tea (including mate),2018,22
1416,"China, Hong Kong SAR",Import Quantity,Tea (including mate),2019,27
1417,"China, Hong Kong SAR",Import Quantity,Tea (including mate),2020,21
1418,"China, Hong Kong SAR",Export Quantity,Tea (including mate),2015,2
1419,"China, Hong Kong SAR",Export Quantity,Tea (including mate),2016,3
1420,"China, Hong Kong SAR",Export Quantity,Tea (including mate),2017,6
1421,"China, Hong Kong SAR",Export Quantity,Tea (including mate),2018,9
1422,"China, Hong Kong SAR",Export Quantity,Tea (including mate),2019,10
1423,"China, Hong Kong SAR",Export Quantity,Tea (including mate),2020,6
1424,"China, Hong Kong SAR",Domestic supply quantity,Tea (including mate),2015,11
1425,"China, Hong Kong SAR",Domestic supply quantity,Tea (including mate),2016,11
1426,"China, Hong Kong SAR",Domestic supply quantity,Tea (including mate),2017,11
1427,"China, Hong Kong SAR",Domestic supply quantity,Tea (including mate),2018,12
1428,"China, Hong Kong SAR",Domestic supply quantity,Tea (including mate),2019,15
1429,"China, Hong Kong SAR",Domestic supply quantity,Tea (including mate),2020,13
1430,"China, Hong Kong SAR",Tourist consumption,Tea (including mate),2015,0
1431,"China, Hong Kong SAR",Tourist consumption,Tea (including mate),2016,0
1432,"China, Hong Kong SAR",Tourist consumption,Tea (including mate),2017,0
1433,"China, Hong Kong SAR",Tourist consumption,Tea (including mate),2018,0
1434,"China, Hong Kong SAR",Tourist consumption,Tea (including mate),2019,0
1435,"China, Macao SAR",Production,Coffee and products,2015,0
1436,"China, Macao SAR",Production,Coffee and products,2016,0
1437,"China, Macao SAR",Production,Coffee and products,2017,0
1438,"China, Macao SAR",Production,Coffee and products,2018,0
1439,"China, Macao SAR",Production,Coffee and products,2019,0
1440,"China, Macao SAR",Production,Coffee and products,2020,0
1441,"China, Macao SAR",Import Quantity,Coffee and products,2015,2
1442,"China, Macao SAR",Import Quantity,Coffee and products,2016,2
1443,"China, Macao SAR",Import Quantity,Coffee and products,2017,2
1444,"China, Macao SAR",Import Quantity,Coffee and products,2018,2
1445,"China, Macao SAR",Import Quantity,Coffee and products,2019,3
1446,"China, Macao SAR",Import Quantity,Coffee and products,2020,2
1447,"China, Macao SAR",Export Quantity,Coffee and products,2015,0
1448,"China, Macao SAR",Export Quantity,Coffee and products,2016,0
1449,"China, Macao SAR",Export Quantity,Coffee and products,2017,0
1450,"China, Macao SAR",Export Quantity,Coffee and products,2018,0
1451,"China, Macao SAR",Export Quantity,Coffee and products,2019,0
1452,"China, Macao SAR",Export Quantity,Coffee and products,2020,0
1453,"China, Macao SAR",Domestic supply quantity,Coffee and products,2015,1
1454,"China, Macao SAR",Domestic supply quantity,Coffee and products,2016,1
1455,"China, Macao SAR",Domestic supply quantity,Coffee and products,2017,1
1456,"China, Macao SAR",Domestic supply quantity,Coffee and products,2018,1
1457,"China, Macao SAR",Domestic supply quantity,Coffee and products,2019,3
1458,"China, Macao SAR",Domestic supply quantity,Coffee and products,2020,2
1459,"China, Macao SAR",Import Quantity,Tea (including mate),2015,1
1460,"China, Macao SAR",Import Quantity,Tea (including mate),2016,1
1461,"China, Macao SAR",Import Quantity,Tea (including mate),2017,1
1462,"China, Macao SAR",Import Quantity,Tea (including mate),2018,1
1463,"China, Macao SAR",Import Quantity,Tea (including mate),2019,1
1464,"China, Macao SAR",Import Quantity,Tea (including mate),2020,1
1465,"China, Macao SAR",Export Quantity,Tea (including mate),2015,0
1466,"China, Macao SAR",Export Quantity,Tea (including mate),2017,0
1467,"China, Macao SAR",Export Quantity,Tea (including mate),2018,0
1468,"China, Macao SAR",Domestic supply quantity,Tea (including mate),2015,1
1469,"China, Macao SAR",Domestic supply quantity,Tea (including mate),2016,1
1470,"China, Macao SAR",Domestic supply quantity,Tea (including mate),2017,1
1471,"China, Macao SAR",Domestic supply quantity,Tea (including mate),2018,1
1472,"China, Macao SAR",Domestic supply quantity,Tea (including mate),2019,1
1473,"China, Macao SAR",Domestic supply quantity,Tea (including mate),2020,1
1474,"China, mainland",Production,Coffee and products,2015,115
1475,"China, mainland",Production,Coffee and products,2016,116
1476,"China, mainland",Production,Coffee and products,2017,116
1477,"China, mainland",Production,Coffee and products,2018,116
1478,"China, mainland",Production,Coffee and products,2019,120
1479,"China, mainland",Production,Coffee and products,2020,114
1480,"China, mainland",Import Quantity,Coffee and products,2015,118
1481,"China, mainland",Import Quantity,Coffee and products,2016,185
1482,"China, mainland",Import Quantity,Coffee and products,2017,136
1483,"China, mainland",Import Quantity,Coffee and products,2018,141
1484,"China, mainland",Import Quantity,Coffee and products,2019,144
1485,"China, mainland",Import Quantity,Coffee and products,2020,154
1486,"China, mainland",Export Quantity,Coffee and products,2015,122
1487,"China, mainland",Export Quantity,Coffee and products,2016,195
1488,"China, mainland",Export Quantity,Coffee and products,2017,116
1489,"China, mainland",Export Quantity,Coffee and products,2018,124
1490,"China, mainland",Export Quantity,Coffee and products,2019,91
1491,"China, mainland",Export Quantity,Coffee and products,2020,71
1492,"China, mainland",Domestic supply quantity,Coffee and products,2015,69
1493,"China, mainland",Domestic supply quantity,Coffee and products,2016,71
1494,"China, mainland",Domestic supply quantity,Coffee and products,2017,76
1495,"China, mainland",Domestic supply quantity,Coffee and products,2018,103
1496,"China, mainland",Domestic supply quantity,Coffee and products,2019,110
1497,"China, mainland",Domestic supply quantity,Coffee and products,2020,157
1498,"China, mainland",Production,Tea (including mate),2015,2277
1499,"China, mainland",Production,Tea (including mate),2016,2313
1500,"China, mainland",Production,Tea (including mate),2017,2460
1501,"China, mainland",Production,Tea (including mate),2018,2610
1502,"China, mainland",Production,Tea (including mate),2019,2777
1503,"China, mainland",Production,Tea (including mate),2020,2970
1504,"China, mainland",Import Quantity,Tea (including mate),2015,24
1505,"China, mainland",Import Quantity,Tea (including mate),2016,24
1506,"China, mainland",Import Quantity,Tea (including mate),2017,32
1507,"China, mainland",Import Quantity,Tea (including mate),2018,38
1508,"China, mainland",Import Quantity,Tea (including mate),2019,46
1509,"China, mainland",Import Quantity,Tea (including mate),2020,46
1510,"China, mainland",Export Quantity,Tea (including mate),2015,336
1511,"China, mainland",Export Quantity,Tea (including mate),2016,341
1512,"China, mainland",Export Quantity,Tea (including mate),2017,367
1513,"China, mainland",Export Quantity,Tea (including mate),2018,378
1514,"China, mainland",Export Quantity,Tea (including mate),2019,381
1515,"China, mainland",Export Quantity,Tea (including mate),2020,361
1516,"China, mainland",Domestic supply quantity,Tea (including mate),2015,1643
1517,"China, mainland",Domestic supply quantity,Tea (including mate),2016,1682
1518,"China, mainland",Domestic supply quantity,Tea (including mate),2017,1729
1519,"China, mainland",Domestic supply quantity,Tea (including mate),2018,1770
1520,"China, mainland",Domestic supply quantity,Tea (including mate),2019,1922
1521,"China, mainland",Domestic supply quantity,Tea (including mate),2020,1952
1522,"China, Taiwan Province of",Production,Coffee and products,2015,0
1523,"China, Taiwan Province of",Production,Coffee and products,2016,0
1524,"China, Taiwan Province of",Production,Coffee and products,2017,0
1525,"China, Taiwan Province of",Production,Coffee and products,2018,0
1526,"China, Taiwan Province of",Production,Coffee and products,2019,0
1527,"China, Taiwan Province of",Production,Coffee and products,2020,0
1528,"China, Taiwan Province of",Import Quantity,Coffee and products,2015,45
1529,"China, Taiwan Province of",Import Quantity,Coffee and products,2016,48
1530,"China, Taiwan Province of",Import Quantity,Coffee and products,2017,58
1531,"China, Taiwan Province of",Import Quantity,Coffee and products,2018,52
1532,"China, Taiwan Province of",Import Quantity,Coffee and products,2019,54
1533,"China, Taiwan Province of",Import Quantity,Coffee and products,2020,59
1534,"China, Taiwan Province of",Export Quantity,Coffee and products,2015,37
1535,"China, Taiwan Province of",Export Quantity,Coffee and products,2016,40
1536,"China, Taiwan Province of",Export Quantity,Coffee and products,2017,44
1537,"China, Taiwan Province of",Export Quantity,Coffee and products,2018,39
1538,"China, Taiwan Province of",Export Quantity,Coffee and products,2019,37
1539,"China, Taiwan Province of",Export Quantity,Coffee and products,2020,6
1540,"China, Taiwan Province of",Domestic supply quantity,Coffee and products,2015,6
1541,"China, Taiwan Province of",Domestic supply quantity,Coffee and products,2016,6
1542,"China, Taiwan Province of",Domestic supply quantity,Coffee and products,2017,11
1543,"China, Taiwan Province of",Domestic supply quantity,Coffee and products,2018,10
1544,"China, Taiwan Province of",Domestic supply quantity,Coffee and products,2019,16
1545,"China, Taiwan Province of",Domestic supply quantity,Coffee and products,2020,36
1546,"China, Taiwan Province of",Production,Tea (including mate),2015,14
1547,"China, Taiwan Province of",Production,Tea (including mate),2016,13
1548,"China, Taiwan Province of",Production,Tea (including mate),2017,13
1549,"China, Taiwan Province of",Production,Tea (including mate),2018,15
1550,"China, Taiwan Province of",Production,Tea (including mate),2019,15
1551,"China, Taiwan Province of",Production,Tea (including mate),2020,14
1552,"China, Taiwan Province of",Import Quantity,Tea (including mate),2015,32
1553,"China, Taiwan Province of",Import Quantity,Tea (including mate),2016,28
1554,"China, Taiwan Province of",Import Quantity,Tea (including mate),2017,32
1555,"China, Taiwan Province of",Import Quantity,Tea (including mate),2018,34
1556,"China, Taiwan Province of",Import Quantity,Tea (including mate),2019,35
1557,"China, Taiwan Province of",Import Quantity,Tea (including mate),2020,32
1558,"China, Taiwan Province of",Export Quantity,Tea (including mate),2015,7
1559,"China, Taiwan Province of",Export Quantity,Tea (including mate),2016,8
1560,"China, Taiwan Province of",Export Quantity,Tea (including mate),2017,9
1561,"China, Taiwan Province of",Export Quantity,Tea (including mate),2018,10
1562,"China, Taiwan Province of",Export Quantity,Tea (including mate),2019,12
1563,"China, Taiwan Province of",Export Quantity,Tea (including mate),2020,10
1564,"China, Taiwan Province of",Domestic supply quantity,Tea (including mate),2015,39
1565,"China, Taiwan Province of",Domestic supply quantity,Tea (including mate),2016,33
1566,"China, Taiwan Province of",Domestic supply quantity,Tea (including mate),2017,36
1567,"China, Taiwan Province of",Domestic supply quantity,Tea (including mate),2018,38
1568,"China, Taiwan Province of",Domestic supply quantity,Tea (including mate),2019,38
1569,"China, Taiwan Province of",Domestic supply quantity,Tea (including mate),2020,37

Replace all rows containing 'China' with only 'China'

In [48]:
tea_coffe_20152020['Area'] = tea_coffe_20152020['Area'].replace('China.*', 'China', regex=True)

In [49]:
tea_coffe_20152020[tea_coffe_20152020['Area'].str.contains("China")]

       Area                   Element                  Item  Year  Value
1331  China                Production   Coffee and products  2015    115
1332  China                Production   Coffee and products  2016    116
1333  China                Production   Coffee and products  2017    116
1334  China                Production   Coffee and products  2018    116
1335  China                Production   Coffee and products  2019    120
1336  China                Production   Coffee and products  2020    114
1337  China           Import Quantity   Coffee and products  2015    184
1338  China           Import Quantity   Coffee and products  2016    286
1339  China           Import Quantity   Coffee and products  2017    269
1340  China           Import Quantity   Coffee and products  2018    224
1341  China           Import Quantity   Coffee and products  2019    225
1342  China           Import Quantity   Coffee and products  2020    235
1343  China           Export Quantity   Coffee and products  2015    162
1344  China           Export Quantity   Coffee and products  2016    246
1345  China           Export Quantity   Coffee and products  2017    182
1346  China           Export Quantity   Coffee and products  2018    173
1347  China           Export Quantity   Coffee and products  2019    132
1348  China           Export Quantity   Coffee and products  2020     79
1349  China  Domestic supply quantity   Coffee and products  2015     90
1350  China  Domestic supply quantity   Coffee and products  2016     93
1351  China  Domestic supply quantity   Coffee and products  2017    103
1352  China  Domestic supply quantity   Coffee and products  2018    133
1353  China  Domestic supply quantity   Coffee and products  2019    146
1354  China  Domestic supply quantity   Coffee and products  2020    211
1355  China       Tourist consumption   Coffee and products  2015      1
1356  China       Tourist consumption   Coffee and products  2016      1
1357  China       Tourist consumption   Coffee and products  2017      2
1358  China       Tourist consumption   Coffee and products  2018      2
1359  China       Tourist consumption   Coffee and products  2019      2
1360  China                Production  Tea (including mate)  2015   2291
1361  China                Production  Tea (including mate)  2016   2326
1362  China                Production  Tea (including mate)  2017   2474
1363  China                Production  Tea (including mate)  2018   2625
1364  China                Production  Tea (including mate)  2019   2792
1365  China                Production  Tea (including mate)  2020   2984
1366  China           Import Quantity  Tea (including mate)  2015     72
1367  China           Import Quantity  Tea (including mate)  2016     69
1368  China           Import Quantity  Tea (including mate)  2017     84
1369  China           Import Quantity  Tea (including mate)  2018     95
1370  China           Import Quantity  Tea (including mate)  2019    109
1371  China           Import Quantity  Tea (including mate)  2020    100
1372  China           Export Quantity  Tea (including mate)  2015    346
1373  China           Export Quantity  Tea (including mate)  2016    351
1374  China           Export Quantity  Tea (including mate)  2017    382
1375  China           Export Quantity  Tea (including mate)  2018    397
1376  China           Export Quantity  Tea (including mate)  2019    403
1377  China           Export Quantity  Tea (including mate)  2020    377
1378  China  Domestic supply quantity  Tea (including mate)  2015   1694
1379  China  Domestic supply quantity  Tea (including mate)  2016   1727
1380  China  Domestic supply quantity  Tea (including mate)  2017   1778
1381  China  Domestic supply quantity  Tea (including mate)  2018   1822
1382  China  Domestic supply quantity  Tea (including mate)  2019   1975
1383  China  Domestic supply quantity  Tea (including mate)  2020   2003
1384  China       Tourist consumption  Tea (including mate)  2015      0
1385  China       Tourist consumption  Tea (including mate)  2016      0
1386  China       Tourist consumption  Tea (including mate)  2017      0
1387  China       Tourist consumption  Tea (including mate)  2018      0
1388  China       Tourist consumption  Tea (including mate)  2019      0
1389  China           Import Quantity   Coffee and products  2015     19
1390  China           Import Quantity   Coffee and products  2016     50
1391  China           Import Quantity   Coffee and products  2017     74
1392  China           Import Quantity   Coffee and products  2018     28
1393  China           Import Quantity   Coffee and products  2019     24
1394  China           Import Quantity   Coffee and products  2020     21
1395  China           Export Quantity   Coffee and products  2015      3
1396  China           Export Quantity   Coffee and products  2016     11
1397  China           Export Quantity   Coffee and products  2017     21
1398  China           Export Quantity   Coffee and products  2018      9
1399  China           Export Quantity   Coffee and products  2019      4
1400  China           Export Quantity   Coffee and products  2020      3
1401  China  Domestic supply quantity   Coffee and products  2015     14
1402  China  Domestic supply quantity   Coffee and products  2016     15
1403  China  Domestic supply quantity   Coffee and products  2017     15
1404  China  Domestic supply quantity   Coffee and products  2018     19
1405  China  Domestic supply quantity   Coffee and products  2019     18
1406  China  Domestic supply quantity   Coffee and products  2020     16
1407  China       Tourist consumption   Coffee and products  2015      1
1408  China       Tourist consumption   Coffee and products  2016      1
1409  China       Tourist consumption   Coffee and products  2017      2
1410  China       Tourist consumption   Coffee and products  2018      2
1411  China       Tourist consumption   Coffee and products  2019      2
1412  China           Import Quantity  Tea (including mate)  2015     15
1413  China           Import Quantity  Tea (including mate)  2016     16
1414  China           Import Quantity  Tea (including mate)  2017     19
1415  China           Import Quantity  Tea (including mate)  2018     22
1416  China           Import Quantity  Tea (including mate)  2019     27
1417  China           Import Quantity  Tea (including mate)  2020     21
1418  China           Export Quantity  Tea (including mate)  2015      2
1419  China           Export Quantity  Tea (including mate)  2016      3
1420  China           Export Quantity  Tea (including mate)  2017      6
1421  China           Export Quantity  Tea (including mate)  2018      9
1422  China           Export Quantity  Tea (including mate)  2019     10
1423  China           Export Quantity  Tea (including mate)  2020      6
1424  China  Domestic supply quantity  Tea (including mate)  2015     11
1425  China  Domestic supply quantity  Tea (including mate)  2016     11
1426  China  Domestic supply quantity  Tea (including mate)  2017     11
1427  China  Domestic supply quantity  Tea (including mate)  2018     12
1428  China  Domestic supply quantity  Tea (including mate)  2019     15
1429  China  Domestic supply quantity  Tea (including mate)  2020     13
1430  China       Tourist consumption  Tea (including mate)  2015      0
1431  China       Tourist consumption  Tea (including mate)  2016      0
1432  China       Tourist consumption  Tea (including mate)  2017      0
1433  China       Tourist consumption  Tea (including mate)  2018      0
1434  China       Tourist consumption  Tea (including mate)  2019      0
1435  China                Production   Coffee and products  2015      0
1436  China                Production   Coffee and products  2016      0
1437  China                Production   Coffee and products  2017      0
1438  China                Production   Coffee and products  2018      0
1439  China                Production   Coffee and products  2019      0
1440  China                Production   Coffee and products  2020      0
1441  China           Import Quantity   Coffee and products  2015      2
1442  China           Import Quantity   Coffee and products  2016      2
1443  China           Import Quantity   Coffee and products  2017      2
1444  China           Import Quantity   Coffee and products  2018      2
1445  China           Import Quantity   Coffee and products  2019      3
1446  China           Import Quantity   Coffee and products  2020      2
1447  China           Export Quantity   Coffee and products  2015      0
1448  China           Export Quantity   Coffee and products  2016      0
1449  China           Export Quantity   Coffee and products  2017      0
1450  China           Export Quantity   Coffee and products  2018      0
1451  China           Export Quantity   Coffee and products  2019      0
1452  China           Export Quantity   Coffee and products  2020      0
1453  China  Domestic supply quantity   Coffee and products  2015      1
1454  China  Domestic supply quantity   Coffee and products  2016      1
1455  China  Domestic supply quantity   Coffee and products  2017      1
1456  China  Domestic supply quantity   Coffee and products  2018      1
1457  China  Domestic supply quantity   Coffee and products  2019      3
1458  China  Domestic supply quantity   Coffee and products  2020      2
1459  China           Import Quantity  Tea (including mate)  2015      1
1460  China           Import Quantity  Tea (including mate)  2016      1
1461  China           Import Quantity  Tea (including mate)  2017      1
1462  China           Import Quantity  Tea (including mate)  2018      1
1463  China           Import Quantity  Tea (including mate)  2019      1
1464  China           Import Quantity  Tea (including mate)  2020      1
1465  China           Export Quantity  Tea (including mate)  2015      0
1466  China           Export Quantity  Tea (including mate)  2017      0
1467  China           Export Quantity  Tea (including mate)  2018      0
1468  China  Domestic supply quantity  Tea (including mate)  2015      1
1469  China  Domestic supply quantity  Tea (including mate)  2016      1
1470  China  Domestic supply quantity  Tea (including mate)  2017      1
1471  China  Domestic supply quantity  Tea (including mate)  2018      1
1472  China  Domestic supply quantity  Tea (including mate)  2019      1
1473  China  Domestic supply quantity  Tea (including mate)  2020      1
1474  China                Production   Coffee and products  2015    115
1475  China                Production   Coffee and products  2016    116
1476  China                Production   Coffee and products  2017    116
1477  China                Production   Coffee and products  2018    116
1478  China                Production   Coffee and products  2019    120
1479  China                Production   Coffee and products  2020    114
1480  China           Import Quantity   Coffee and products  2015    118
1481  China           Import Quantity   Coffee and products  2016    185
1482  China           Import Quantity   Coffee and products  2017    136
1483  China           Import Quantity   Coffee and products  2018    141
1484  China           Import Quantity   Coffee and products  2019    144
1485  China           Import Quantity   Coffee and products  2020    154
1486  China           Export Quantity   Coffee and products  2015    122
1487  China           Export Quantity   Coffee and products  2016    195
1488  China           Export Quantity   Coffee and products  2017    116
1489  China           Export Quantity   Coffee and products  2018    124
1490  China           Export Quantity   Coffee and products  2019     91
1491  China           Export Quantity   Coffee and products  2020     71
1492  China  Domestic supply quantity   Coffee and products  2015     69
1493  China  Domestic supply quantity   Coffee and products  2016     71
1494  China  Domestic supply quantity   Coffee and products  2017     76
1495  China  Domestic supply quantity   Coffee and products  2018    103
1496  China  Domestic supply quantity   Coffee and products  2019    110
1497  China  Domestic supply quantity   Coffee and products  2020    157
1498  China                Production  Tea (including mate)  2015   2277
1499  China                Production  Tea (including mate)  2016   2313
1500  China                Production  Tea (including mate)  2017   2460
1501  China                Production  Tea (including mate)  2018   2610
1502  China                Production  Tea (including mate)  2019   2777
1503  China                Production  Tea (including mate)  2020   2970
1504  China           Import Quantity  Tea (including mate)  2015     24
1505  China           Import Quantity  Tea (including mate)  2016     24
1506  China           Import Quantity  Tea (including mate)  2017     32
1507  China           Import Quantity  Tea (including mate)  2018     38
1508  China           Import Quantity  Tea (including mate)  2019     46
1509  China           Import Quantity  Tea (including mate)  2020     46
1510  China           Export Quantity  Tea (including mate)  2015    336
1511  China           Export Quantity  Tea (including mate)  2016    341
1512  China           Export Quantity  Tea (including mate)  2017    367
1513  China           Export Quantity  Tea (including mate)  2018    378
1514  China           Export Quantity  Tea (including mate)  2019    381
1515  China           Export Quantity  Tea (including mate)  2020    361
1516  China  Domestic supply quantity  Tea (including mate)  2015   1643
1517  China  Domestic supply quantity  Tea (including mate)  2016   1682
1518  China  Domestic supply quantity  Tea (including mate)  2017   1729
1519  China  Domestic supply quantity  Tea (including mate)  2018   1770
1520  China  Domestic supply quantity  Tea (including mate)  2019   1922
1521  China  Domestic supply quantity  Tea (including mate)  2020   1952
1522  China                Production   Coffee and products  2015      0
1523  China                Production   Coffee and products  2016      0
1524  China                Production   Coffee and products  2017      0
1525  China                Production   Coffee and products  2018      0
1526  China                Production   Coffee and products  2019      0
1527  China                Production   Coffee and products  2020      0
1528  China           Import Quantity   Coffee and products  2015     45
1529  China           Import Quantity   Coffee and products  2016     48
1530  China           Import Quantity   Coffee and products  2017     58
1531  China           Import Quantity   Coffee and products  2018     52
1532  China           Import Quantity   Coffee and products  2019     54
1533  China           Import Quantity   Coffee and products  2020     59
1534  China           Export Quantity   Coffee and products  2015     37
1535  China           Export Quantity   Coffee and products  2016     40
1536  China           Export Quantity   Coffee and products  2017     44
1537  China           Export Quantity   Coffee and products  2018     39
1538  China           Export Quantity   Coffee and products  2019     37
1539  China           Export Quantity   Coffee and products  2020      6
1540  China  Domestic supply quantity   Coffee and products  2015      6
1541  China  Domestic supply quantity   Coffee and products  2016      6
1542  China  Domestic supply quantity   Coffee and products  2017     11
1543  China  Domestic supply quantity   Coffee and products  2018     10
1544  China  Domestic supply quantity   Coffee and products  2019     16
1545  China  Domestic supply quantity   Coffee and products  2020     36
1546  China                Production  Tea (including mate)  2015     14
1547  China                Production  Tea (including mate)  2016     13
1548  China                Production  Tea (including mate)  2017     13
1549  China                Production  Tea (including mate)  2018     15
1550  China                Production  Tea (including mate)  2019     15
1551  China                Production  Tea (including mate)  2020     14
1552  China           Import Quantity  Tea (including mate)  2015     32
1553  China           Import Quantity  Tea (including mate)  2016     28
1554  China           Import Quantity  Tea (including mate)  2017     32
1555  China           Import Quantity  Tea (including mate)  2018     34
1556  China           Import Quantity  Tea (including mate)  2019     35
1557  China           Import Quantity  Tea (including mate)  2020     32
1558  China           Export Quantity  Tea (including mate)  2015      7
1559  China           Export Quantity  Tea (including mate)  2016      8
1560  China           Export Quantity  Tea (including mate)  2017      9
1561  China           Export Quantity  Tea (including mate)  2018     10
1562  China           Export Quantity  Tea (including mate)  2019     12
1563  China           Export Quantity  Tea (including mate)  2020     10
1564  China  Domestic supply quantity  Tea (including mate)  2015     39
1565  China  Domestic supply quantity  Tea (including mate)  2016     33
1566  China  Domestic supply quantity  Tea (including mate)  2017     36
1567  China  Domestic supply quantity  Tea (including mate)  2018     38
1568  China  Domestic supply quantity  Tea (including mate)  2019     38
1569  China  Domestic supply quantity  Tea (including mate)  2020     37

In [50]:
tea_coffe_20152020 = tea_coffe_20152020.rename(columns={'Area': 'Country'})

In [58]:
tea_coffe_20152020=tea_coffe_20152020[tea_coffe_20152020['Element']!='Tourist consumption']

In [68]:
region["COUNTRY (DISPLAY)"].unique()

array(['Albania', 'Andorra', 'Armenia', 'Australia', 'Austria',
       'Azerbaijan', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium',
       'Bhutan', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Cambodia', 'Canada', 'Chile', 'China', 'Colombia',
       'Congo', 'Costa Rica', 'Croatia', 'Cyprus', 'Czechia',
       "CÃ´te d'Ivoire", "Democratic People's Republic of Korea",
       'Denmark', 'Ecuador', 'El Salvador', 'Estonia', 'Eswatini',
       'Ethiopia', 'Finland', 'France', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Iran (Islamic Republic of)', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon',
       'Lithuania', 'Luxembourg', 'Malaysia', 'Malta', 'Mexico', 'Monaco',
       'Mongolia', 'Montenegro', 'Morocco', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Nigeria', 'Niue', 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'Romania', 'Russian Federation', 'Rwanda',
       'Samoa', 'San Marino', 'Serbia', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'South Africa', 'Spain', 'Sri Lanka',
       'Sweden', 'Switzerland', 'Tajikistan', 'Tunisia', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Zambia', 'Afghanistan',
       'Algeria', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Bahamas',
       'Barbados', 'Belize', 'Benin', 'Bolivia (Plurinational State of)',
       'Brunei Darussalam', 'Burkina Faso', 'Burundi', 'Cabo Verde',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       'Cook Islands', 'Cuba', 'Democratic Republic of the Congo',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Egypt',
       'Equatorial Guinea', 'Eritrea', 'Fiji', 'Gabon', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Indonesia', 'Jamaica',
       'Kiribati', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi',
       'Maldives', 'Mali', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Micronesia (Federated States of)', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Niger', 'Palau', 'Panama', 'Papua New Guinea',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Sao Tome and Principe',
       'Saudi Arabia', 'Senegal', 'Seychelles', 'Solomon Islands',
       'Somalia', 'South Sudan', 'Sudan', 'Suriname',
       'Syrian Arab Republic', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Turkey', 'United Arab Emirates',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Zimbabwe'], dtype=object)

In [60]:
tea_coffe_20152020['Country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Costa Rica', "CÃ´te d'Ivoire", 'Croatia',
       'Cuba', 'Cyprus', 'Czechia',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'French Polynesia', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic",
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (Federated States of)', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'Romania', 'Russian Federation', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'South Africa', 'South Sudan', 'Spain',
       'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'Timor-Leste',
       'Togo', 'Trinidad and Tobago', 'Tunisia', 'TÃ¼rkiye',
       'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [69]:
df_full_join = pd.merge(tea_coffe_20152020, region, left_on='Country', right_on='COUNTRY (DISPLAY)', how='outer')

In [72]:
df_full_join.shape

(7465, 7)

In [77]:
df_full_join=df_full_join[~df_full_join['COUNTRY (DISPLAY)'].isnull()]

In [79]:
df_full_join=df_full_join[~df_full_join['Country'].isnull()]

In [81]:
Teacoffee=df_full_join.iloc[:,:5]

In [83]:
region=df_full_join.iloc[:,5:]

In [87]:
region=region.drop_duplicates()

In [93]:
Teacoffee=pd.read_excel("TeaCoffee_20152020.xlsx")

In [95]:
region=pd.read_csv("RegionCountry.csv")

In [97]:
df_full_join = pd.merge(Teacoffee, region, left_on='Country', right_on='COUNTRY (DISPLAY)', how='outer')

In [99]:
df_full_join[df_full_join['Country'].isnull()]

Empty DataFrame
Columns: [Country, Element, Item, Year, Value, REGION (DISPLAY), COUNTRY (DISPLAY)]
Index: []

In [100]:
df_full_join[df_full_join['COUNTRY (DISPLAY)'].isnull()]

Empty DataFrame
Columns: [Country, Element, Item, Year, Value, REGION (DISPLAY), COUNTRY (DISPLAY)]
Index: []

In [102]:
region.isnull().sum()

REGION (DISPLAY)     0
COUNTRY (DISPLAY)    0
dtype: int64

In [104]:
Teacoffee.head(25)

        Country                   Element                  Item  Year  Value
0   Afghanistan           Import Quantity   Coffee and products  2015      0
1   Afghanistan           Import Quantity   Coffee and products  2016      0
2   Afghanistan           Import Quantity   Coffee and products  2017      2
3   Afghanistan           Import Quantity   Coffee and products  2018      1
4   Afghanistan           Import Quantity   Coffee and products  2019      1
5   Afghanistan           Import Quantity   Coffee and products  2020      2
6   Afghanistan           Export Quantity   Coffee and products  2015      0
7   Afghanistan           Export Quantity   Coffee and products  2016      0
8   Afghanistan           Export Quantity   Coffee and products  2017      0
9   Afghanistan           Export Quantity   Coffee and products  2018      1
10  Afghanistan           Export Quantity   Coffee and products  2019      0
11  Afghanistan           Export Quantity   Coffee and products  2020      4
12  Afghanistan  Domestic supply quantity   Coffee and products  2015      0
13  Afghanistan  Domestic supply quantity   Coffee and products  2016      0
14  Afghanistan  Domestic supply quantity   Coffee and products  2017      0
15  Afghanistan  Domestic supply quantity   Coffee and products  2018      0
16  Afghanistan  Domestic supply quantity   Coffee and products  2019      0
17  Afghanistan  Domestic supply quantity   Coffee and products  2020      0
18  Afghanistan           Import Quantity  Tea (including mate)  2015     72
19  Afghanistan           Import Quantity  Tea (including mate)  2016     52
20  Afghanistan           Import Quantity  Tea (including mate)  2017     80
21  Afghanistan           Import Quantity  Tea (including mate)  2018     81
22  Afghanistan           Import Quantity  Tea (including mate)  2019     76
23  Afghanistan           Import Quantity  Tea (including mate)  2020     15
24  Afghanistan           Export Quantity  Tea (including mate)  2015      0

In [105]:
region.head()

        REGION (DISPLAY)    COUNTRY (DISPLAY)
0  Eastern Mediterranean          Afghanistan
1                 Europe              Albania
2                 Africa              Algeria
3                 Africa               Angola
4               Americas  Antigua and Barbuda

#### Pivot table with items in 'element' column as column names

In [19]:
pivot_Tea_coffee = pd.pivot_table(tea_coffe_20152020, index=['Area', 'Item', 'Year'], columns='Element', values='Value').reset_index()

In [20]:
pivot_Tea_coffee

Element,Area,Item,Year,Domestic supply quantity,Export Quantity,Import Quantity,Production,Tourist consumption
0,Afghanistan,Coffee and products,2015,0.0,0.0,0.0,NaN,NaN
1,Afghanistan,Coffee and products,2016,0.0,0.0,0.0,NaN,NaN
2,Afghanistan,Coffee and products,2017,0.0,0.0,2.0,NaN,NaN
3,Afghanistan,Coffee and products,2018,0.0,1.0,1.0,NaN,NaN
4,Afghanistan,Coffee and products,2019,0.0,0.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...
2179,Zimbabwe,Tea (including mate),2016,-9.0,11.0,1.0,2.0,NaN
2180,Zimbabwe,Tea (including mate),2017,-12.0,13.0,1.0,1.0,NaN
2181,Zimbabwe,Tea (including mate),2018,-13.0,14.0,0.0,1.0,NaN
2182,Zimbabwe,Tea (including mate),2019,-11.0,15.0,0.0,4.0,NaN
2183,Zimbabwe,Tea (including mate),2020,-8.0,12.0,0.0,4.0,NaN

In [21]:
pivot_Tea_coffee.reset_index(drop=True)

Element,Area,Item,Year,Domestic supply quantity,Export Quantity,Import Quantity,Production,Tourist consumption
0,Afghanistan,Coffee and products,2015,0.0,0.0,0.0,NaN,NaN
1,Afghanistan,Coffee and products,2016,0.0,0.0,0.0,NaN,NaN
2,Afghanistan,Coffee and products,2017,0.0,0.0,2.0,NaN,NaN
3,Afghanistan,Coffee and products,2018,0.0,1.0,1.0,NaN,NaN
4,Afghanistan,Coffee and products,2019,0.0,0.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...
2179,Zimbabwe,Tea (including mate),2016,-9.0,11.0,1.0,2.0,NaN
2180,Zimbabwe,Tea (including mate),2017,-12.0,13.0,1.0,1.0,NaN
2181,Zimbabwe,Tea (including mate),2018,-13.0,14.0,0.0,1.0,NaN
2182,Zimbabwe,Tea (including mate),2019,-11.0,15.0,0.0,4.0,NaN
2183,Zimbabwe,Tea (including mate),2020,-8.0,12.0,0.0,4.0,NaN

In [22]:
pivot_Tea_coffee.head(50)

Element,Area,Item,Year,Domestic supply quantity,Export Quantity,Import Quantity,Production,Tourist consumption
0,Afghanistan,Coffee and products,2015,0.0,0.0,0.0,NaN,NaN
1,Afghanistan,Coffee and products,2016,0.0,0.0,0.0,NaN,NaN
2,Afghanistan,Coffee and products,2017,0.0,0.0,2.0,NaN,NaN
3,Afghanistan,Coffee and products,2018,0.0,1.0,1.0,NaN,NaN
4,Afghanistan,Coffee and products,2019,0.0,0.0,1.0,NaN,NaN
5,Afghanistan,Coffee and products,2020,0.0,4.0,2.0,NaN,NaN
6,Afghanistan,Tea (including mate),2015,90.0,0.0,72.0,NaN,NaN
7,Afghanistan,Tea (including mate),2016,51.0,0.0,52.0,NaN,NaN
8,Afghanistan,Tea (including mate),2017,79.0,1.0,80.0,NaN,NaN
9,Afghanistan,Tea (including mate),2018,81.0,0.0,81.0,NaN,NaN
10,Afghanistan,Tea (including mate),2019,76.0,0.0,76.0,NaN,NaN
11,Afghanistan,Tea (including mate),2020,15.0,0.0,15.0,NaN,NaN
12,Albania,Coffee and products,2015,9.0,0.0,9.0,0.0,NaN
13,Albania,Coffee and products,2016,9.0,0.0,9.0,0.0,NaN
14,Albania,Coffee and products,2017,6.0,0.0,6.0,0.0,NaN
15,Albania,Coffee and products,2018,8.0,0.0,8.0,0.0,NaN
16,Albania,Coffee and products,2019,8.0,0.0,8.0,0.0,NaN
17,Albania,Coffee and products,2020,8.0,0.0,8.0,0.0,NaN
18,Albania,Tea (including mate),2015,0.0,NaN,0.0,NaN,NaN
19,Albania,Tea (including mate),2016,0.0,0.0,0.0,NaN,NaN
20,Albania,Tea (including mate),2017,0.0,0.0,0.0,NaN,NaN
21,Albania,Tea (including mate),2018,0.0,NaN,0.0,NaN,NaN
22,Albania,Tea (including mate),2019,0.0,0.0,0.0,NaN,NaN
23,Albania,Tea (including mate),2020,0.0,0.0,0.0,NaN,NaN
24,Algeria,Coffee and products,2015,130.0,0.0,130.0,NaN,NaN
25,Algeria,Coffee and products,2016,140.0,0.0,140.0,NaN,NaN
26,Algeria,Coffee and products,2017,132.0,0.0,132.0,NaN,NaN
27,Algeria,Coffee and products,2018,116.0,0.0,117.0,NaN,NaN
28,Algeria,Coffee and products,2019,122.0,0.0,122.0,NaN,NaN
29,Algeria,Coffee and products,2020,84.0,0.0,85.0,NaN,NaN
30,Algeria,Tea (including mate),2015,15.0,0.0,15.0,NaN,NaN
31,Algeria,Tea (including mate),2016,16.0,0.0,15.0,NaN,NaN
32,Algeria,Tea (including mate),2017,16.0,0.0,14.0,NaN,NaN
33,Algeria,Tea (including mate),2018,15.0,0.0,15.0,NaN,NaN
34,Algeria,Tea (including mate),2019,15.0,0.0,17.0,NaN,NaN
35,Algeria,Tea (including mate),2020,15.0,0.0,15.0,NaN,NaN
36,Angola,Coffee and products,2015,20.0,1.0,9.0,15.0,NaN
37,Angola,Coffee and products,2016,20.0,0.0,6.0,15.0,NaN
38,Angola,Coffee and products,2017,18.0,1.0,3.0,15.0,NaN
39,Angola,Coffee and products,2018,19.0,1.0,2.0,16.0,NaN
40,Angola,Coffee and products,2019,18.0,1.0,5.0,15.0,NaN
41,Angola,Coffee and products,2020,16.0,2.0,2.0,15.0,NaN
42,Angola,Tea (including mate),2015,1.0,0.0,0.0,NaN,NaN
43,Angola,Tea (including mate),2016,1.0,0.0,1.0,NaN,NaN
44,Angola,Tea (including mate),2017,1.0,0.0,1.0,NaN,NaN
45,Angola,Tea (including mate),2018,1.0,0.0,0.0,NaN,NaN
46,Angola,Tea (including mate),2019,1.0,0.0,2.0,NaN,NaN
47,Angola,Tea (including mate),2020,1.0,0.0,0.0,NaN,NaN
48,Antigua and Barbuda,Coffee and products,2015,0.0,0.0,0.0,NaN,0.0
49,Antigua and Barbuda,Coffee and products,2016,0.0,0.0,0.0,NaN,0.0

In [23]:
pivot_Tea_coffee.shape

(2184, 8)

In [24]:
pivot_Tea_coffee.isnull().sum()

Element
Area                           0
Item                           0
Year                           0
Domestic supply quantity       0
Export Quantity              173
Import Quantity                2
Production                  1111
Tourist consumption         1778
dtype: int64

Because I have too little observation in the column "Tourist consumption"

In [25]:
pivot_Tea_coffee=pivot_Tea_coffee.drop('Tourist consumption',axis=1)

Let see the countries that doesn't values for export

In [26]:
pivot_Tea_coffee[pivot_Tea_coffee['Export Quantity'].isna()]

Element,Area,Item,Year,Domestic supply quantity,Export Quantity,Import Quantity,Production
18,Albania,Tea (including mate),2015,0.0,NaN,0.0,NaN
21,Albania,Tea (including mate),2018,0.0,NaN,0.0,NaN
53,Antigua and Barbuda,Coffee and products,2020,0.0,NaN,0.0,NaN
56,Antigua and Barbuda,Tea (including mate),2017,0.0,NaN,0.0,NaN
57,Antigua and Barbuda,Tea (including mate),2018,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...
2119,Vanuatu,Tea (including mate),2016,0.0,NaN,0.0,NaN
2122,Vanuatu,Tea (including mate),2019,0.0,NaN,0.0,NaN
2125,Venezuela (Bolivarian Republic of),Coffee and products,2016,59.0,NaN,7.0,51.0
2126,Venezuela (Bolivarian Republic of),Coffee and products,2017,58.0,NaN,1.0,57.0
2135,Venezuela (Bolivarian Republic of),Tea (including mate),2020,0.0,NaN,0.0,NaN

In [27]:
production_tea_coffee=pivot_Tea_coffee[~pivot_Tea_coffee['Production'].isna()]

In [28]:
production_tea_coffee=production_tea_coffee.drop(['Domestic supply quantity','Export Quantity','Import Quantity'],axis=1)

In [29]:
production_tea_coffee

Element      Area                  Item  Year  Production
12        Albania   Coffee and products  2015         0.0
13        Albania   Coffee and products  2016         0.0
14        Albania   Coffee and products  2017         0.0
15        Albania   Coffee and products  2018         0.0
16        Albania   Coffee and products  2019         0.0
...           ...                   ...   ...         ...
2179     Zimbabwe  Tea (including mate)  2016         2.0
2180     Zimbabwe  Tea (including mate)  2017         1.0
2181     Zimbabwe  Tea (including mate)  2018         1.0
2182     Zimbabwe  Tea (including mate)  2019         4.0
2183     Zimbabwe  Tea (including mate)  2020         4.0

[1073 rows x 4 columns]

In [30]:
pivot_Tea_coffee=pivot_Tea_coffee.drop("Production",axis=1)

In [31]:
pivot_Tea_coffee

Element,Area,Item,Year,Domestic supply quantity,Export Quantity,Import Quantity
0,Afghanistan,Coffee and products,2015,0.0,0.0,0.0
1,Afghanistan,Coffee and products,2016,0.0,0.0,0.0
2,Afghanistan,Coffee and products,2017,0.0,0.0,2.0
3,Afghanistan,Coffee and products,2018,0.0,1.0,1.0
4,Afghanistan,Coffee and products,2019,0.0,0.0,1.0
...,...,...,...,...,...,...
2179,Zimbabwe,Tea (including mate),2016,-9.0,11.0,1.0
2180,Zimbabwe,Tea (including mate),2017,-12.0,13.0,1.0
2181,Zimbabwe,Tea (including mate),2018,-13.0,14.0,0.0
2182,Zimbabwe,Tea (including mate),2019,-11.0,15.0,0.0
2183,Zimbabwe,Tea (including mate),2020,-8.0,12.0,0.0

In [32]:
pivot_Tea_coffee=pivot_Tea_coffee.dropna()

In [33]:
pivot_Tea_coffee

Element,Area,Item,Year,Domestic supply quantity,Export Quantity,Import Quantity
0,Afghanistan,Coffee and products,2015,0.0,0.0,0.0
1,Afghanistan,Coffee and products,2016,0.0,0.0,0.0
2,Afghanistan,Coffee and products,2017,0.0,0.0,2.0
3,Afghanistan,Coffee and products,2018,0.0,1.0,1.0
4,Afghanistan,Coffee and products,2019,0.0,0.0,1.0
...,...,...,...,...,...,...
2179,Zimbabwe,Tea (including mate),2016,-9.0,11.0,1.0
2180,Zimbabwe,Tea (including mate),2017,-12.0,13.0,1.0
2181,Zimbabwe,Tea (including mate),2018,-13.0,14.0,0.0
2182,Zimbabwe,Tea (including mate),2019,-11.0,15.0,0.0
2183,Zimbabwe,Tea (including mate),2020,-8.0,12.0,0.0

#### Export the datas

In [34]:
pivot_Tea_coffee.to_excel('Tea_coffee_20152020.xlsx', index=False)

In [35]:
production_tea_coffee.to_excel('Production_tea_coffe_20152020.xlsx',index=False)

In [59]:
tea_coffe_20152020.to_excel('TeaCoffee_20152020.xlsx',index=False)

In [89]:
region.to_excel('region.xlsx',index=False)

In [90]:
region.to_csv('RegionCountry.csv',index=False)

In [91]:
Teacoffee.to_excel('TeaCoffee_20152020.xlsx',index=False)